-- ==============================================================================
-- SQL Schema để đồng bộ Kho tài liệu (Documents) với Lịch họp (Bookings) và Phòng họp
-- ==============================================================================

-- 1. Bảng Documents (Kho tài liệu)
-- Lưu trữ tất cả tài liệu của đơn vị
CREATE TABLE IF NOT EXISTS public.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    type text,
    size text,
    date text, -- Lưu định dạng 'DD/MM/YYYY' khớp với frontend
    status text DEFAULT 'draft', -- 'draft', 'pending', 'approved'
    category text, -- 'res', 'fin', 'hr', 'meet', ...
    file_url text,
    unit_id text NOT NULL -- ID đơn vị để phân quyền dữ liệu
);

-- 2. Bảng Bookings (Lịch họp)
-- Lưu trữ thông tin các cuộc họp
CREATE TABLE IF NOT EXISTS public.bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    title text NOT NULL,
    day integer, -- Ngày trong tháng (ví dụ: 25)
    start_time text, -- Giờ bắt đầu (ví dụ: '08:00')
    end_time text, -- Giờ kết thúc (ví dụ: '09:00')
    room_id text,
    type text, -- 'internal', 'external', 'important', 'training'
    attendees jsonb DEFAULT '[]'::jsonb, -- Lưu danh sách người tham dự dạng JSON
    unit_id text NOT NULL
);

-- 3. Bảng Booking_Documents (Bảng trung gian)
-- ĐÂY LÀ MẤU CHỐT ĐỂ ĐỒNG BỘ: Liên kết N-N giữa Lịch họp và Tài liệu
-- Khi thêm tài liệu vào Lịch, một bản ghi sẽ được tạo ở đây.
-- Khi vào Meeting Room, hệ thống sẽ query bảng này để lấy tài liệu.
CREATE TABLE IF NOT EXISTS public.booking_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    booking_id bigint REFERENCES public.bookings(id) ON DELETE CASCADE,
    document_id bigint REFERENCES public.documents(id) ON DELETE CASCADE,
    unit_id text NOT NULL,
    UNIQUE(booking_id, document_id) -- Tránh trùng lặp tài liệu trong một cuộc họp
);

-- 4. Kích hoạt Realtime (Quan trọng cho tính năng đồng bộ tức thì)
-- Giúp Meeting Room tự động cập nhật khi có tài liệu mới được thêm vào Lịch
ALTER PUBLICATION supabase_realtime ADD TABLE public.documents;
ALTER PUBLICATION supabase_realtime ADD TABLE public.bookings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.booking_documents;

-- 5. Thiết lập bảo mật (RLS - Row Level Security)
-- Đảm bảo an toàn dữ liệu
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_documents ENABLE ROW LEVEL SECURITY;

-- Chính sách mẫu (Cho phép truy cập tất cả - Cần tùy chỉnh theo logic auth thực tế của bạn)
CREATE POLICY "Public Access Documents" ON public.documents FOR ALL USING (true);
CREATE POLICY "Public Access Bookings" ON public.bookings FOR ALL USING (true);
CREATE POLICY "Public Access Booking Documents" ON public.booking_documents FOR ALL USING (true);

-- ==============================================================================
-- Query mẫu để lấy tài liệu cho một cuộc họp (Dùng trong Meeting Room)
-- ==============================================================================
/*
SELECT 
    d.*
FROM 
    documents d
JOIN 
    booking_documents bd ON d.id = bd.document_id
WHERE 
    bd.booking_id = [ID_CUỘC_HỌP_HIỆN_TẠI];
*/
