-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create 'documents' table
CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    date TEXT,
    size TEXT,
    type TEXT,
    status TEXT,
    category TEXT,
    file_url TEXT,
    unit_id TEXT
);

-- Create 'rooms' table
CREATE TABLE IF NOT EXISTS rooms (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    capacity INTEGER,
    unit_id TEXT
);

-- Create 'bookings' table
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    unit_id TEXT,
    day INTEGER,
    title TEXT,
    start_time TEXT,
    end_time TEXT,
    room_id TEXT,
    type TEXT,
    attendees JSONB DEFAULT '[]'::jsonb,
    documents JSONB DEFAULT '[]'::jsonb
);

-- Create 'users' table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    role TEXT,
    dept TEXT,
    status TEXT,
    avatar_color TEXT,
    email TEXT,
    unit_id TEXT,
    current_session_id TEXT
);

-- Enable Row Level Security (RLS) - Optional but recommended
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Create policies (Allow all for now for simplicity, adjust for production)
CREATE POLICY "Enable all access for all users" ON documents FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON rooms FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON bookings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON users FOR ALL USING (true) WITH CHECK (true);

-- Storage Bucket Setup (This usually needs to be done in Supabase Dashboard, but here is the SQL representation if supported)
-- INSERT INTO storage.buckets (id, name, public) VALUES ('documents', 'documents', true) ON CONFLICT (id) DO NOTHING;

-- Storage Policies
-- CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'documents' );
-- CREATE POLICY "Authenticated Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'documents' );
