-- Bảng Units (Đơn vị)
CREATE TABLE IF NOT EXISTS public.units (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Thêm hoặc cập nhật dữ liệu mẫu cho bảng Units
INSERT INTO public.units (id, name) VALUES
    ('unit_1', 'Đơn vị 1 (UBND phường 1)'),
    ('unit_2', 'Đơn vị 2 (UBND xã 2)'),
    ('unit_3', 'Đơn vị 3 (UBND XP 3)')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- Bảng Users (Người dùng)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    dept TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'offline')),
    avatar_color TEXT NOT NULL,
    email TEXT,
    unit_id TEXT NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
    current_session_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Bảng Rooms (Phòng họp)
CREATE TABLE IF NOT EXISTS public.rooms (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    capacity INTEGER NOT NULL,
    location TEXT NOT NULL,
    amenities TEXT[] DEFAULT '{}',
    status TEXT NOT NULL CHECK (status IN ('active', 'maintenance')),
    image TEXT,
    unit_id TEXT NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Bảng Documents (Tài liệu)
CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    date TEXT NOT NULL,
    size TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('approved', 'draft', 'pending')),
    category TEXT NOT NULL,
    file_url TEXT, -- Đường dẫn file lưu trên Supabase Storage
    unit_id TEXT NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Bảng Bookings (Lịch họp)
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    day INTEGER NOT NULL,
    title TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    room_id TEXT NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('internal', 'external', 'training', 'important')),
    unit_id TEXT NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Bảng trung gian Booking_Attendees (Người tham gia họp)
CREATE TABLE IF NOT EXISTS public.booking_attendees (
    booking_id BIGINT NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    PRIMARY KEY (booking_id, user_id)
);

-- Bảng trung gian Booking_Documents (Tài liệu đính kèm cuộc họp)
CREATE TABLE IF NOT EXISTS public.booking_documents (
    booking_id BIGINT NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
    document_id BIGINT NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
    PRIMARY KEY (booking_id, document_id)
);

-- Tạo Storage Bucket cho tài liệu
INSERT INTO storage.buckets (id, name, public) 
VALUES ('documents', 'documents', true)
ON CONFLICT (id) DO NOTHING;

-- Thiết lập Row Level Security (RLS) cơ bản (Tạm thời cho phép tất cả để dễ phát triển)
ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_attendees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all read/write on units" ON public.units FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all read/write on users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all read/write on rooms" ON public.rooms FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all read/write on documents" ON public.documents FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all read/write on bookings" ON public.bookings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all read/write on booking_attendees" ON public.booking_attendees FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all read/write on booking_documents" ON public.booking_documents FOR ALL USING (true) WITH CHECK (true);

-- Cho phép upload/download file trên Storage
CREATE POLICY "Allow public read access on documents bucket" ON storage.objects FOR SELECT USING (bucket_id = 'documents');
CREATE POLICY "Allow public upload on documents bucket" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'documents');
CREATE POLICY "Allow public update on documents bucket" ON storage.objects FOR UPDATE USING (bucket_id = 'documents');
CREATE POLICY "Allow public delete on documents bucket" ON storage.objects FOR DELETE USING (bucket_id = 'documents');
